# OpenAI secrets
OPENAI_API_KEY = "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"

# Astra DB secrets
ASTRA_ENDPOINT = "https://9015fec9-46b9-462d-9d3d-f9122c6f07f0-us-east-2.apps.astra.datastax.com"
ASTRA_TOKEN = "AstraCS:SwfaKWzwrDbHUrldnlmEHkhT:8b6d08c9e23c3bc6d705830dada7593e1916a552fd4726d53dc568fe233203e2"

# Optionally: LangSmith secrets for tracing
LANGCHAIN_TRACING_V2 = "true"
LANGCHAIN_ENDPOINT = ""
LANGCHAIN_API_KEY = ""
LANGCHAIN_PROJECT = ""

[passwords]
# Follow the rule: username = "password"
# Where username defines the Astra Vector Table and the rails.csv experience
postnl = ""
datastax = "datastax"

[languages]
# Follow the rule: username = "localization_code"
# Where localization_code defines the language from localization.csv
postnl = "nl_NL"
datastax = "en_US"

[delete_option]
# Follow the rule: username = "delete_option"
# Where delete_option = True allows the 'Delete Context' button to be shown for that username
datastax = "True"